/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifica se a API está no ar */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description API no ar */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Saude"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuário da sessão atual */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Usuário logado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/contagem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quantidade de acionamentos por status (o prestador vê só os seus) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contagem por status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ContagemAcionamentos"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista (o prestador vê só os seus), do mais recente para o mais antigo */
        get: {
            parameters: {
                query?: {
                    status?: "aberto" | "em_andamento" | "aguardando" | "reprovado" | "finalizados";
                    busca?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Acionamentos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumoAcionamento"][];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Cria o acionamento, copiando o checklist de cada tipo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoAcionamento"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResumoAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe com etapas, fotos, revisões e linha do tempo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detalhe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}/revisao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Aprova ou reprova (reprovar exige motivo) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovaRevisao"];
                };
            };
            responses: {
                /** @description Revisado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não está aguardando aprovação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Motivo obrigatório */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assinantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assinantes ativos por nome (a busca do Novo acionamento; no máximo 8) */
        get: {
            parameters: {
                query?: {
                    busca?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assinantes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Assinante"][];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cep/{cep}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Endereço de um CEP (ViaCEP), para atendimento em outro endereço */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 8 dígitos, com ou sem hífen */
                    cep: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Endereço */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnderecoCep"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description CEP não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description CEP malformado */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description O ViaCEP não respondeu */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tipos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tipos de demanda com o checklist */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tipos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TipoDemanda"][];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Cria um tipo de demanda (checklist vazio, cor pela paleta) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoTipo"];
                };
            };
            responses: {
                /** @description Tipo de demanda */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TipoDemanda"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Já existe um tipo com esse nome */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prestadores ativos (seletor do Novo acionamento); com ?cep=, do mais próximo ao mais distante */
        get: {
            parameters: {
                query?: {
                    status?: "ativo";
                    /** @description CEP de referência (8 dígitos, com ou sem hífen) */
                    cep?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prestadores ativos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrestadorOpcao"][];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description CEP malformado */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        /** Credencia um prestador (ativo, desde hoje) e, com e-mail, envia o convite de acesso */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DadosPrestador"];
                };
            };
            responses: {
                /** @description Credenciado, com o resultado do convite */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrestadorCredenciado"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Documento já cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}/iniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia o atendimento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Acionamento atualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}/enviar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envia para aprovação */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Acionamento atualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}/etapas/{etapaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marca a etapa e/ou grava o comentário */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    etapaId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AtualizacaoEtapa"];
                };
            };
            responses: {
                /** @description Acionamento atualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/acionamentos/{id}/conclusao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Grava o comentário final para o gestor */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AtualizacaoConclusao"];
                };
            };
            responses: {
                /** @description Acionamento atualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/acionamentos/{id}/fotos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Envia uma foto da etapa ou da conclusão (JPEG, PNG, WebP ou HEIC, até 10 MB) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        arquivo?: string;
                        /** @enum {string} */
                        contexto: "etapa" | "conclusao";
                        etapaId?: string;
                        /** Format: date-time */
                        tiradaEm?: string;
                    };
                };
            };
            responses: {
                /** @description Foto gravada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Foto"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Foto grande demais */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Arquivo não é imagem */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}/fotos/{fotoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove uma foto da etapa ou da conclusão */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    fotoId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removida */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                        };
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acionamentos/{id}/inviavel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Marca como inviável (motivo + pelo menos 1 foto) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        comentario: string;
                        arquivos?: string[];
                    };
                };
            };
            responses: {
                /** @description Acionamento atualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalheAcionamento"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Status não permite esta ação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Fotos grandes demais */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Arquivo não é imagem */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestador/inicio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Próximo atendimento, agenda de hoje, métricas e rota do dia */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Início */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InicioPrestador"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só o prestador */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/painel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPIs, volume por dia, reprovações por tipo e ranking do período */
        get: {
            parameters: {
                query?: {
                    /** @description Últimos 7 ou 30 dias */
                    periodo?: "7" | "30";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Painel do gestor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PainelGestor"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Período inválido */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tipos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui o tipo (os acionamentos já criados não mudam) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Excluído */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                        };
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Tipo não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Último tipo ativo */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Renomeia o tipo e/ou grava o checklist inteiro */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AtualizacaoTipo"];
                };
            };
            responses: {
                /** @description Tipo de demanda */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TipoDemanda"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Tipo não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Já existe um tipo com esse nome */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/prestadores/planilha/previa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confere a planilha sem gravar: selo de cada linha, resumo e ausentes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description .xlsx, .xls, .csv ou .tsv (inclusive UTF-16), até 5 MB
                         */
                        arquivo?: string;
                    };
                };
            };
            responses: {
                /** @description Prévia da importação */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PreviaPlanilha"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Planilha acima de 5 MB, ou .xlsx acima de 50 MB descompactado */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Sem arquivo, ilegível, sem linhas ou acima de 2000 linhas */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores/planilha/importacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Importa a planilha numa transação (recalcula a prévia) e grava a auditoria */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description .xlsx, .xls, .csv ou .tsv (inclusive UTF-16), até 5 MB
                         */
                        arquivo?: string;
                        /**
                         * @description Desativa os ativos que não estão na planilha (padrão: false)
                         * @enum {string}
                         */
                        desativarAusentes?: "true" | "false";
                    };
                };
            };
            responses: {
                /** @description Contagens aplicadas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResultadoImportacao"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Os cadastros mudaram durante a importação */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Planilha acima de 5 MB, ou .xlsx acima de 50 MB descompactado */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Sem arquivo, ilegível, sem linhas ou acima de 2000 linhas */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores/planilha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta os prestadores não excluídos (credenciados-russo-DD-MM-AAAA.xlsx) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Planilha de credenciados */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores/planilha/modelo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Modelo da planilha (modelo-credenciados-russo.xlsx) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Modelo com o cabeçalho e uma linha de exemplo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores/{id}/convite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envia ou reenvia o convite de acesso do prestador por e-mail
         * @description Cria ou atualiza o usuário do prestador (sem senha) e manda um link de uso único, válido por 7 dias, para ele criar a senha. Invalida os convites anteriores. Quem já tem senha recebe o mesmo convite, que funciona como redefinição.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Convite enviado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConviteEnviado"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Prestador não encontrado ou excluído */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Prestador sem e-mail, com e-mail inválido ou usado por outra conta */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description O servidor de e-mail não aceitou a mensagem */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores/cadastro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prestadores não excluídos, por nome, com especialidades e carga */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cadastro */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrestadorCadastro"][];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prestadores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Exclui (lógico) quem não tem acionamentos em aberto e derruba a sessão dele */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Excluído */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            ok: true;
                        };
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Prestador não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Prestador com acionamentos em aberto */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Edita o cadastro (status, cor e data de credenciamento não mudam) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DadosPrestador"];
                };
            };
            responses: {
                /** @description Cadastro do prestador */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrestadorCadastro"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Prestador não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Documento já cadastrado */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/prestadores/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ativa ou desativa (o switch da lista e o "Desativar" da exclusão) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusPrestador"];
                };
            };
            responses: {
                /** @description Cadastro do prestador */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrestadorCadastro"];
                    };
                };
                /** @description Sem sessão */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Só para a gestão */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Prestador não encontrado */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
                /** @description Dados inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Erro"];
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Saude: {
            /** @enum {boolean} */
            ok: true;
        };
        Usuario: {
            id: string;
            nome: string;
            email: string;
            /** @enum {string} */
            papel: "gestor" | "prestador";
            prestador: {
                id: string;
                nome: string;
            } | null;
        };
        Erro: {
            erro: {
                codigo: string;
                mensagem: string;
                campos?: {
                    campo: string;
                    mensagem: string;
                }[];
            };
        };
        ContagemAcionamentos: {
            aberto: number;
            em_andamento: number;
            aguardando: number;
            reprovado: number;
            aprovado: number;
        };
        ResumoAcionamento: {
            id: string;
            codigo: string;
            titulo: string;
            cliente: string;
            endereco: string;
            data: string;
            inicio: string;
            fim: string;
            /** @enum {string} */
            status: "aberto" | "em_andamento" | "aguardando" | "reprovado" | "aprovado";
            inviavel: boolean;
            prestador: {
                id: string;
                nome: string;
                cor: string;
            };
            tipos: {
                nome: string;
                cor: string;
            }[];
            etapas: {
                feitas: number;
                total: number;
            };
            ultimoEnvioEm: string | null;
        };
        DetalheAcionamento: components["schemas"]["ResumoAcionamento"] & {
            criadoEm: string;
            iniciadoEm: string | null;
            comentarioConclusao: string | null;
            regras: {
                photoMin: number;
                requireAllSteps: boolean;
            };
            demandas: {
                id: string;
                tipoNome: string;
                cor: string;
                etapas: {
                    id: string;
                    texto: string;
                    feita: boolean;
                    comentario: string | null;
                    fotos: components["schemas"]["Foto"][];
                }[];
            }[];
            fotosConclusao: components["schemas"]["Foto"][];
            inviabilidade: {
                comentario: string;
                fotos: components["schemas"]["Foto"][];
            } | null;
            revisoes: {
                /** @enum {string} */
                decisao: "aprovado" | "reprovado";
                motivo: string | null;
                em: string;
            }[];
            eventos: {
                /** @enum {string} */
                tipo: "criado" | "iniciado" | "enviado" | "inviabilidade_enviada" | "aprovado" | "reprovado";
                em: string;
                motivo: string | null;
            }[];
        };
        Foto: {
            id: string;
            /** @description Caminho assinado; null nas fotos de exemplo */
            url: string | null;
            /** @description Cor do bloco das fotos de exemplo */
            cor: string | null;
            horario: string;
            tiradaEm: string;
        };
        NovoAcionamento: {
            titulo: string;
            cliente: string;
            endereco: string;
            /** @description Assinante escolhido na busca (cliente e endereço são snapshots) */
            assinanteId?: string;
            /** @description CEP do atendimento: 8 dígitos, com ou sem hífen */
            cep?: string;
            /** Format: date */
            data: string;
            inicio: string;
            fim: string;
            tipoIds: string[];
            prestadorId: string;
        };
        NovaRevisao: {
            /** @enum {string} */
            decisao: "aprovado" | "reprovado";
            motivo?: string;
        };
        Assinante: {
            id: string;
            nome: string;
            /** @description Só os 8 dígitos */
            cep: string;
            logradouro: string;
            numero: string;
            complemento: string | null;
            bairro: string;
            cidade: string;
            /** @description Pronto para exibir: "Logradouro, número · bairro" */
            endereco: string;
        };
        EnderecoCep: {
            /** @description Só os 8 dígitos */
            cep: string;
            /** @description Vazio nos CEPs gerais de cidade */
            logradouro: string;
            bairro: string;
            cidade: string;
        };
        TipoDemanda: {
            id: string;
            nome: string;
            cor: string;
            /** @description Grupo maior; null vira "Outros" */
            categoria: string | null;
            checklist: string[];
        };
        PrestadorOpcao: {
            id: string;
            nome: string;
            regiao: string | null;
            /** @description Só os 8 dígitos */
            cep: string | null;
            cor: string;
        };
        AtualizacaoEtapa: {
            feita?: boolean;
            comentario?: string;
        };
        AtualizacaoConclusao: {
            comentario: string;
        };
        InicioPrestador: {
            proximo: components["schemas"]["ResumoAcionamento"] | null;
            hoje: components["schemas"]["ResumoAcionamento"][];
            metricas: {
                hoje: number;
                noMes: number;
                aprovacao: {
                    taxa: number;
                    dePrimeira: number | null;
                };
                paraCorrigir: number;
            };
            rotaDoDia: string[];
        };
        PainelGestor: {
            /** @example 2026-09-29 */
            hoje: string;
            periodo: 7 | 30;
            /** @description Aberto, em execução ou reprovado */
            emAberto: number;
            /** @description Atendimentos de hoje não aprovados */
            paraHoje: number;
            aguardando: number;
            aprovacao: {
                aprovadas: number;
                total: number;
            };
            /**
             * @description Média de (1º envio − início) em minutos, com fração; null sem dados
             * @example 106.15
             */
            tempoMedioMin: number | null;
            inviaveis: {
                quantidade: number;
                totalPeriodo: number;
            };
            volume: {
                /** @example 2026-09-29 */
                data: string;
                total: number;
                aprovados: number;
            }[];
            reprovacoesPorTipo: {
                tipoNome: string;
                reprovacoes: number;
                demandas: number;
            }[];
            ranking: {
                prestador: {
                    id: string;
                    nome: string;
                    cor: string;
                };
                concluidos: number;
                revisoes: {
                    aprovadas: number;
                    total: number;
                };
                /**
                 * @description Média de (1º envio − início) em minutos, com fração; null sem dados
                 * @example 106.15
                 */
                tempoMedioMin: number | null;
            }[];
        };
        NovoTipo: {
            nome: string;
        };
        AtualizacaoTipo: {
            nome?: string;
            /** @description Grupo maior da tela; null ou vazio limpa (vira "Outros") */
            categoria?: string | null;
            /** @description O checklist inteiro, na ordem (etapas vazias são descartadas) */
            checklist?: string[];
        };
        PreviaPlanilha: {
            linhas: {
                /** @description Como veio na planilha (vazio = sem nome) */
                nome: string;
                /** @description Como veio na planilha */
                documento: string;
                /** @description Nomes como vieram, inclusive os não reconhecidos */
                especialidades: string[];
                /** @description As de `especialidades` que não casam com nenhum tipo ativo (erro de digitação, tipo excluído): a importação as ignora. A API sempre manda. */
                especialidadesIgnoradas?: string[];
                /** @enum {string} */
                acao: "novo" | "atualizar" | "erro";
                /** @enum {string} */
                selo: "Novo" | "Atualizar" | "Sem nome" | "Documento inválido" | "Duplicado na planilha" | "Telefone inválido" | "E-mail inválido";
            }[];
            resumo: {
                novos: number;
                atualizados: number;
                erros: number;
            };
            /** @description Ativos cujo documento não está na planilha, na ordem de cadastro */
            ausentes: {
                id: string;
                nome: string;
            }[];
            /** @description Linhas "Novo" com e-mail: a importação não manda convite, que sai pelo Editar de cada um. A API sempre manda. */
            novosComEmail?: number;
        };
        ResultadoImportacao: {
            novos: number;
            atualizados: number;
            desativados: number;
        };
        ConviteEnviado: {
            /** @description E-mail que recebeu o convite e vira o login */
            email: string;
            /** @description Validade do link (ISO 8601) */
            expiraEm: string;
        };
        PrestadorCadastro: {
            id: string;
            nome: string;
            /** @description Só dígitos (11 ou 14) */
            documento: string;
            /** @description Só dígitos, com DDD */
            telefone: string;
            email: string | null;
            regiao: string | null;
            /** @description Só os 8 dígitos */
            cep: string | null;
            /** @enum {string} */
            status: "ativo" | "inativo";
            cor: string;
            /** @description AAAA-MM-DD */
            credenciadoDesde: string;
            /** @description Na ordem cadastrada, sem os tipos excluídos */
            especialidades: {
                id: string;
                nome: string;
            }[];
            /** @description Acionamentos agendados, em execução, reprovados ou aguardando */
            emAberto: number;
            total: number;
            /**
             * @description Acesso ao app: ativo (tem senha), convidado (convite válido), pendente (tem e-mail, sem convite válido nem senha) ou sem_email
             * @enum {string}
             */
            acesso: "sem_email" | "pendente" | "convidado" | "ativo";
        };
        PrestadorCredenciado: components["schemas"]["PrestadorCadastro"] & {
            convite: {
                /** @enum {string} */
                situacao: "enviado" | "falhou" | "sem_email";
                email: string | null;
                /** @description Por que o convite não saiu (o cadastro vale mesmo assim) */
                mensagem: string | null;
            };
        };
        DadosPrestador: {
            nome: string;
            /** @description CPF ou CNPJ, com ou sem máscara */
            documento: string;
            telefone: string;
            email?: string | null;
            regiao?: string | null;
            /** @description 8 dígitos, com ou sem hífen */
            cep?: string | null;
            /** @description Ids dos tipos, na ordem escolhida */
            especialidades: string[];
        };
        StatusPrestador: {
            /** @enum {string} */
            status: "ativo" | "inativo";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
